### ISSUE TITLE
Dúvida sobre o trabalho

### ISSUE THREAD

**Issue by gcarlos64** [ajholanda/edu-compiladores#1]
Bom dia professor, estou com uma dúvida em relação à definição da gramática do trabalho, mais especificamente na parte da declaração de veriáveis.

Tentamos definir as regras para a declaração de variáveis da seguinte forma:

```
declaration_assignment
        : ID ':' type_specifier '=' expression ';'
        ;

declaration_assignment_list
        : declaration_assignment
        | declaration_assignment_list declaration_assignment
        ;

declaration_list
        : VAR declaration_assignment_list
        ;
```

Porém, caímos em uma ambiguidade relacionada ao token `ID`, que eu imagino que seja por limitação do algorítmo de parsing. Basicamente, após a lista de declarações, podemos ter uma expressão ou atribuição que comece com o token `ID`, que nos leva a um conflito de shift/redução, por exemplo:

```
var 
        i : i64 = 1;
        j : f64 = 1.0;
i = 10;
```

No entanto, não consegui entender exatamente o por quê deste conflito.

Segue mais algumas regras relevantes para contexto:

```
statement
        : expression_statement
        | assignment_statement
        | selection_statement
        | loop_statement
        | compound_statement
        | return_statement
        ;

assignment_statement
        : ID '=' expression_statement
        ;

expression_statement
        : ';'
        | expression ';'
        ;

statement_list
        : statement
        | statement_list statement
        ;

compound_statement
        : '{' '}'
        | '{' statement_list '}'
        | '{' declaration_list '}'
        | '{' declaration_list statement_list '}'
        ;
```

É possível evitar este conflito alterando a linguagem para que a lista de declarações de variáveis seja seprara por algo diferente de `;`, por exemplo:

```
var 
        i : i64 = 1,
        j : f64 = 10.0;
```

No entanto, imagino que isso não seja uma possibilidade para o trabalho, já que na definição da linguagem consta a obrigatoriedade de se utilizar `;`.

---
Caso precise, nosso projeto se encontra no repositório https://github.com/gcarlos64/xyz-lang

Atenciosamente,
Carlos

**Comment by ajholanda** [comment]
Olá Carlos;

Por se tratar de uma linguagem bem simples, admita que as atribuições iniciais só possam ser feitas usando valores contantes, em

```
declaration_assignment
        : ID ':' type_specifier '=' expression ';'
        ;
```

trocar `expression` por `CONST_INT` e `CONST_FLOAT` para cada tipo de dado.

Att.
Adriano

**Comment by gcarlos64** [comment]
Olá  professor. Fazendo as alterações sugeridas, ainda caímos no mesmo conflito. Obtemos estes exemplos com a flag `-Wcounterexamples` passada ao bison:

```
xyz.y: warning: 1 shift/reduce conflict [-Wconflicts-sr]
xyz.y: warning: shift/reduce conflict on token ID [-Wcounterexamples]
time limit exceeded: 6.000000
  First example: FN ID '(' ')' VAR declaration_assignment_list • ID ':' type_specifier '=' constant ';' declaration_list statement_list '}' $end
  Shift derivation
    $accept
    ↳ 0: program                                                                                                                                                          $end
         ↳ 1: function_declaration_list
              ↳ 33: function_declaration
                    ↳ 32: FN ID '(' ')' function_compound_statement
                                        ↳ 30: declaration_list                                                                        declaration_list statement_list '}'
                                              ↳ 7: VAR declaration_assignment_list
                                                       ↳ 6: declaration_assignment_list declaration_assignment
                                                                                        ↳ 4: • ID ':' type_specifier '=' constant ';'
  Second example: FN ID '(' ')' '{' VAR declaration_assignment_list • ID '=' expression_statement '}' $end
  Reduce derivation
    $accept
    ↳ 0: program                                                                                                                          $end
         ↳ 1: function_declaration_list
              ↳ 33: function_declaration
                    ↳ 32: FN ID '(' ')' function_compound_statement
                                        ↳ 30: '{' declaration_list                       statement_list                               '}'
                                                  ↳ 7: VAR declaration_assignment_list • ↳ 21: statement
                                                                                               ↳ 12: assignment_statement
                                                                                                     ↳ 8: ID '=' expression_statement
```

Acredito que o conflito não tem a ver com o uso das expressões nas declarações, mas sim pelo fato da lista de declarações serem separadas por `;`, tal como qualquer outro statement. Dessa forma o algoritmo nao sabe se algo começando com `ID` é um statement isolado ou se faz parte da lista de declarações. 

No entanto, a gramática em sí não me parece ambígua, pois um caso possui `:` `type_specifier` após `ID` e no outro não, portanto acredito que o algoritmo de parsing que não esteja consiguindo identificar qual operação realizar, já que possui uma limitação no número de elementos no lookahead.

**Comment by ajholanda** [comment]
Olá Carlos;

Correto. Altere a sintaxe da linguagem.

Teste outro separador ou envolva a declaração de variáveis, com `[...]` ou `{...}`, por exemplo.

---
Adriano

**Comment by gcarlos64** [comment]
Obrigado! Eu já até havia alterado a sintáxe para utilizar `,` ao invés de `;` anteriormente para poder ir dando continuidade no projeto, irei manter dessa maneira.

**Comment by ajholanda** [comment]
Essa sintaxe é inspirada no Delphi, que permite:

```
var
  Value: Integer = 10;
  Correct: Boolean = True;
```

Fonte: https://www.marcocantu.com/epascal/English/ch03data.htm

**Comment by gcarlos64** [comment]
Entendi! Mas como seria possível escrever uma gramática válida para esta linguagem com as restrições que temos no parser do `bison` ?

**Comment by ajholanda** [comment]
Esta alteração era prevista, sendo uma estratégia viável para o `yacc`. Há pelo menos 3 opções de solução:

1. A que vocês fizeram, pelo alteração do separador de declaração de variáveis.
2. Circundar a declaração de variáveis, por `[...]` ou `begin ... end;`, por exemplo.
3. Circundar o código da função, como é feito pelas linguagens baseadas em Pascal, como o Delphi. Exemplo:

```
fn fatorial(n i64) {
    var
      i : i64 = 1;
      r : i64 = 1;

  begin
    if n < 0 {
        return -1;
    }

    while i < n + 1 {
      r = r * i;
      i++;
    }

    return r;
  end;
}
```

É assim que o Delphi resolve este conflito sintático.
